### ISSUE TITLE
AdsToJava.dll did not link

### ISSUE THREAD

**Issue by robertsonj3** [Beckhoff/AdsToJava#3] opened 2023-11-15 03:25 UTC
After building the AdsToTc jar and dll, I placed the dll in the System32 directory.
When running a java project using AdsToJava it threw a linking exception.
To resolve the issue, I renamed the dll in the System32 directory from "AdsToJava.dll" to "AdsToJava-3.dll"

**Comment by vossjannik** [comment] 2023-12-14 12:15
Hi @robertsonj3,

the file "AdsToJava.dll" should've been renamed to "AdsToJava-3.dll" automatically.
However, there was an issue with the path syntax in the Batch script (run/copy_to_dist.bat).
The bash version of the script worked as intended.

Your issue should be resolved by 668a5b9820f0fea4eda6f618a210f8c66142451d

Best Regards, Jannik Voss

**Closed by vossjannik** 2023-12-14 12:15 UTC
